### ISSUE TITLE
Review Module 12 - Docker Compose

### ISSUE THREAD

**Issue by millidavids** [millidavids/docker-compose-module#1]
@jlaswell

**Comment by jlaswell** [comment]
The current `docker-compose.yml` file seems to have the data volume just mounting the same directory instead of mounting the directory from another service.

**Comment by millidavids** [comment]
@jlaswell 

50e6a2e65c66f569d721c9d698e5e91cc07730a6

**Comment by jlaswell** [comment]
:boom: simple as that
